In [27]:
# Importando a biblioteca pandas para manipulação de dados
import pandas as pd

banco_dados = pd.read_csv('banco_clientes_ficticios_v4.csv')
display(banco_dados)

,ID Cliente,Nome,Data Assinatura,Plano,Preço,Status,Idade,Estado
0,CLI-000001,Thiago Nascimento,2023-01-15,Padrão,"R$ 49,90",Ativo,68.0,SP
1,CLI-000002,Thiago Nascimento,2019-06-03,Básico,"R$ 29,90",Cancelado,42.0,CE
2,CLI-000003,Marcos Souza,2023-12-24,Básico,"R$ 29,90",Ativo,62.0,NaN
3,CLI-000004,Carla Rodrigues,2021-05-07,Básico,"R$ 29,90",Ativo,62.0,BA
4,CLI-000005,Isabela Lima,2019-05-12,Básico,"R$ 29,90",Ativo,48.0,SC
...,...,...,...,...,...,...,...,...
77245,CLI-029538,Patrícia Rodrigues,2019-10-06,Básico,"R$ 29,90",Ativo,21.0,PE
77246,CLI-054247,Kaique Nascimento,2020-06-11,Padrão,"R$ 49,90",Cancelado,36.0,SP
77247,CLI-054956,Marcos Pereira,NaN,Padrão,"R$ 49,90",Ativo,49.0,PR
77248,CLI-039068,João Souza,2025-09-30,Padrão,"R$ 49,90",Ativo,47.0,MG
77249,CLI-045679,Felipe Almeida,2019-03-02,Básico,"R$ 29,90",Ativo,54.0,NaN

In [28]:
# Verificando a quantidade de valores nulos em cada coluna

display(banco_dados.isnull().sum())

ID Cliente            0
Nome               3815
Data Assinatura    3984
Plano              3846
Preço              3890
Status             3705
Idade              3907
Estado             3968
dtype: int64

In [29]:
# Contar a quantidade de clientes por Status, Plano e Estado
display(banco_dados['Status'].value_counts())
display(banco_dados['Plano'].value_counts())
display(banco_dados['Estado'].value_counts())

Status
Ativo        58873
Cancelado    14672
Name: count, dtype: int64

Plano
Premium    24699
Básico     24486
Padrão     24219
Name: count, dtype: int64

Estado
GO    7491
MG    7411
RJ    7407
PR    7348
PE    7324
SC    7311
SP    7293
BA    7276
CE    7260
RS    7161
Name: count, dtype: int64

In [30]:
# Alterando o culuna de preço para o tipo numérico, removendo o símbolo de moeda e convertendo para float

banco_dados['Preço'] = banco_dados['Preço'].str.replace('R$', '').str.replace(',', '.').astype(float)


display(banco_dados)

,ID Cliente,Nome,Data Assinatura,Plano,Preço,Status,Idade,Estado
0,CLI-000001,Thiago Nascimento,2023-01-15,Padrão,49.9,Ativo,68.0,SP
1,CLI-000002,Thiago Nascimento,2019-06-03,Básico,29.9,Cancelado,42.0,CE
2,CLI-000003,Marcos Souza,2023-12-24,Básico,29.9,Ativo,62.0,NaN
3,CLI-000004,Carla Rodrigues,2021-05-07,Básico,29.9,Ativo,62.0,BA
4,CLI-000005,Isabela Lima,2019-05-12,Básico,29.9,Ativo,48.0,SC
...,...,...,...,...,...,...,...,...
77245,CLI-029538,Patrícia Rodrigues,2019-10-06,Básico,29.9,Ativo,21.0,PE
77246,CLI-054247,Kaique Nascimento,2020-06-11,Padrão,49.9,Cancelado,36.0,SP
77247,CLI-054956,Marcos Pereira,NaN,Padrão,49.9,Ativo,49.0,PR
77248,CLI-039068,João Souza,2025-09-30,Padrão,49.9,Ativo,47.0,MG
77249,CLI-045679,Felipe Almeida,2019-03-02,Básico,29.9,Ativo,54.0,NaN