In [36]:
# Importando a biblioteca pandas para manipulação de dados
import pandas as pd

banco_dados = pd.read_csv('banco_clientes_ficticios_v4.csv')
display(banco_dados)

,ID Cliente,Nome,Data Assinatura,Plano,Preço,Status,Idade,Estado
0,CLI-000001,Thiago Nascimento,2023-01-15,Padrão,"R$ 49,90",Ativo,68.0,SP
1,CLI-000002,Thiago Nascimento,2019-06-03,Básico,"R$ 29,90",Cancelado,42.0,CE
2,CLI-000003,Marcos Souza,2023-12-24,Básico,"R$ 29,90",Ativo,62.0,NaN
3,CLI-000004,Carla Rodrigues,2021-05-07,Básico,"R$ 29,90",Ativo,62.0,BA
4,CLI-000005,Isabela Lima,2019-05-12,Básico,"R$ 29,90",Ativo,48.0,SC
...,...,...,...,...,...,...,...,...
77245,CLI-029538,Patrícia Rodrigues,2019-10-06,Básico,"R$ 29,90",Ativo,21.0,PE
77246,CLI-054247,Kaique Nascimento,2020-06-11,Padrão,"R$ 49,90",Cancelado,36.0,SP
77247,CLI-054956,Marcos Pereira,NaN,Padrão,"R$ 49,90",Ativo,49.0,PR
77248,CLI-039068,João Souza,2025-09-30,Padrão,"R$ 49,90",Ativo,47.0,MG
77249,CLI-045679,Felipe Almeida,2019-03-02,Básico,"R$ 29,90",Ativo,54.0,NaN

In [37]:
# Verificando a quantidade de valores nulos em cada coluna

display(banco_dados.isnull().sum())

ID Cliente            0
Nome               3815
Data Assinatura    3984
Plano              3846
Preço              3890
Status             3705
Idade              3907
Estado             3968
dtype: int64

In [38]:
# Contar a quantidade de clientes por Status, Plano e Estado
display(banco_dados['Status'].value_counts())
display(banco_dados['Plano'].value_counts())
display(banco_dados['Estado'].value_counts())

Status
Ativo        58873
Cancelado    14672
Name: count, dtype: int64

Plano
Premium    24699
Básico     24486
Padrão     24219
Name: count, dtype: int64

Estado
GO    7491
MG    7411
RJ    7407
PR    7348
PE    7324
SC    7311
SP    7293
BA    7276
CE    7260
RS    7161
Name: count, dtype: int64

In [39]:
# Alterando o culuna de preço para o tipo numérico, removendo o símbolo de moeda e convertendo para float

banco_dados['Preço'] = banco_dados['Preço'].str.replace('R$', '').str.replace(',', '.').astype(float)
banco_dados = banco_dados.dropna().drop_duplicates()



display(banco_dados)

,ID Cliente,Nome,Data Assinatura,Plano,Preço,Status,Idade,Estado
0,CLI-000001,Thiago Nascimento,2023-01-15,Padrão,49.9,Ativo,68.0,SP
1,CLI-000002,Thiago Nascimento,2019-06-03,Básico,29.9,Cancelado,42.0,CE
3,CLI-000004,Carla Rodrigues,2021-05-07,Básico,29.9,Ativo,62.0,BA
4,CLI-000005,Isabela Lima,2019-05-12,Básico,29.9,Ativo,48.0,SC
6,CLI-000007,Otávio Rodrigues,2020-09-20,Padrão,49.9,Ativo,59.0,RJ
...,...,...,...,...,...,...,...,...
74991,CLI-074992,Larissa Santos,2019-02-07,Padrão,49.9,Ativo,80.0,RS
74992,CLI-074993,Larissa Souza,2018-11-09,Padrão,49.9,Ativo,42.0,BA
74993,CLI-074994,Marcos Nascimento,2024-05-07,Premium,79.9,Ativo,18.0,PR
74995,CLI-074996,Marcos Almeida,2020-09-21,Premium,79.9,Ativo,63.0,PR
74999,CLI-075000,Natália Santos,2018-01-05,Básico,29.9,Ativo,63.0,MG

In [40]:
#Convertendo Data Assinatura para o tipo data
banco_dados["Data Assinatura"] = pd.to_datetime(banco_dados["Data Assinatura"], errors="coerce")
display(banco_dados)

,ID Cliente,Nome,Data Assinatura,Plano,Preço,Status,Idade,Estado
0,CLI-000001,Thiago Nascimento,2023-01-15,Padrão,49.9,Ativo,68.0,SP
1,CLI-000002,Thiago Nascimento,2019-06-03,Básico,29.9,Cancelado,42.0,CE
3,CLI-000004,Carla Rodrigues,2021-05-07,Básico,29.9,Ativo,62.0,BA
4,CLI-000005,Isabela Lima,2019-05-12,Básico,29.9,Ativo,48.0,SC
6,CLI-000007,Otávio Rodrigues,2020-09-20,Padrão,49.9,Ativo,59.0,RJ
...,...,...,...,...,...,...,...,...
74991,CLI-074992,Larissa Santos,2019-02-07,Padrão,49.9,Ativo,80.0,RS
74992,CLI-074993,Larissa Souza,2018-11-09,Padrão,49.9,Ativo,42.0,BA
74993,CLI-074994,Marcos Nascimento,2024-05-07,Premium,79.9,Ativo,18.0,PR
74995,CLI-074996,Marcos Almeida,2020-09-21,Premium,79.9,Ativo,63.0,PR
74999,CLI-075000,Natália Santos,2018-01-05,Básico,29.9,Ativo,63.0,MG

In [41]:
# Calculando a Idade media dos clientes
idade_media = banco_dados['Idade'].mean()
print(f'Idade média dos clientes: {idade_media:.1f} anos')

Idade média dos clientes: 49.0 anos

In [42]:
# Calculando idade média por plano
idade_media_plano = banco_dados.groupby('Plano')['Idade'].mean()
print(f'Idade média por plano:\n{idade_media_plano} anos')

Idade média por plano:
Plano
Básico     49.006942
Padrão     48.981093
Premium    49.112391
Name: Idade, dtype: float64 anos

In [ ]:
# Receita total por plano
receita_total_plano = banco_dados.groupby('Plano')['Preço'].sum()
print(f'Receita total por plano:\n{receita_total_plano.round(2)}')

Receita total por plano:
Plano
Básico      525462.6
Padrão      860375.8
Premium    1408317.4
Name: Preço, dtype: float64:.2f